import { validateAppearanceSnapshotV1, validateArtifactBundleV1, validateLocalPreflightReportV1, validateRobloxClassicProfileV1, validateSemanticPalette } from '../../domain/contracts.js';
import { canonicalJson } from '../../domain/canonical-json.js';
import { digestBytes } from '../../domain/digest.js';
import { err, ok } from '../../domain/result.js';
import { decodePngRgba, encodePngRgba } from '../minecraft/png.js';
import { paintRobloxClassic } from './painter.js';
import { REGION_GROUPS, ROBLOX_CLASSIC_TEMPLATE_V1 } from './template-v1.js';
import { createStoredZip, parseStoredZip, text, utf8 } from './package.js';

const EXPECTED=['README.txt','manifest.json','my-avatar-roblox-pants.png','my-avatar-roblox-shirt.png'];
export const ROBLOX_CLASSIC_README=`My Avatars Roblox Classic export\n\n1. Unzip the My Avatars package locally.\n2. Upload the shirt and pants images separately through the appropriate Roblox Classic clothing workflow.\n3. Do not upload manifest.json or README.txt.\n4. This compiler does not create a Classic T-shirt or ShirtGraphic.\n5. Test the candidates on a Block Avatar in Studio.\n6. Many modern or user-generated bodies do not display 2D Classic clothing correctly.\n7. Hair, faces, accessories, bodies, upload, moderation, fees, and publication are not generated or performed by this compiler.\n`;
const prohibited=/accepted|approved|roblox-valid|works with roblox avatars|one-click|universal body|marketplace acceptance|free publication|credential|password|api key/i;
const check=(id,passed,message)=>({id,passed,message});
const fault=(kind,error)=>err({kind,message:error.message});
const readInput=(input)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.getPrototypeOf(input)!==Object.prototype)throw new TypeError('Compile input must be a plain object');const keys=Reflect.ownKeys(input);if(keys.length!==2||!keys.includes('snapshot')||!keys.includes('profile'))throw new TypeError('Compile input must contain exactly snapshot and profile');for(const key of keys){const d=Object.getOwnPropertyDescriptor(input,key);if(typeof key!=='string'||!d.enumerable||!Object.hasOwn(d,'value'))throw new TypeError('Compile input must use enumerable data fields');}return input;};

const exact=(value,keys,path)=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new TypeError(`${path} must be a plain object`);const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some((key)=>typeof key!=='string'||!keys.includes(key)))throw new TypeError(`${path} has unknown or missing keys`);for(const key of own){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor.enumerable||!Object.hasOwn(descriptor,'value'))throw new TypeError(`${path}.${key} must be enumerable data`);}};
const dense=(value,path)=>{if(!Array.isArray(value))throw new TypeError(`${path} must be an array`);const allowed=new Set(['length',...Array.from({length:value.length},(_,index)=>String(index))]);for(const key of Reflect.ownKeys(value)){if(typeof key!=='string'||!allowed.has(key))throw new TypeError(`${path} is decorated`);}for(let index=0;index<value.length;index++)if(!Object.hasOwn(value,index))throw new TypeError(`${path} is sparse`);};
const DIGEST=/^[0-9a-f]{64}$/;
const LOCAL_IDS=['shirt-dimensions','shirt-required-regions','shirt-transparent-outside','pants-dimensions','pants-required-regions','pants-transparent-outside'];
const hasFullAlphaCoverage=(rgba,[x,y,width,height])=>{for(let row=y;row<y+height;row++)for(let column=x;column<x+width;column++)if(rgba[(row*585+column)*4+3]===0)return false;return true;};
const transparentOutside=(rgba)=>{const mask=new Uint8Array(585*559);for(const faces of Object.values(REGION_GROUPS))for(const [x,y,width,height] of Object.values(faces))for(let row=y;row<y+height;row++)for(let column=x;column<x+width;column++)mask[row*585+column]=1;for(let index=0;index<mask.length;index++)if(!mask[index]&&rgba[index*4+3]!==0)return false;return true;};
const garmentChecks=(name,image)=>{const dimensions=image?.width===585&&image?.height===559&&image?.rgba?.length===585*559*4;const regions=dimensions&&Object.values(REGION_GROUPS).every((faces)=>Object.values(faces).every((rectangle)=>hasFullAlphaCoverage(image.rgba,rectangle)));const outside=dimensions&&transparentOutside(image.rgba);return [check(`${name}-dimensions`,dimensions,`${name} is exactly 585 x 559 RGBA.`),check(`${name}-required-regions`,regions,`${name} has every required mapped rectangle.`),check(`${name}-transparent-outside`,outside,`${name} is transparent outside mapped rectangles.`)];};
export const createRobloxLocalPreflight=(shirt,pants)=>{const checks=[...garmentChecks('shirt',shirt),...garmentChecks('pants',pants)];return {passed:checks.every(({passed})=>passed),checks};};

export function validateRobloxPackageManifest(manifest){
  exact(manifest,['format','version','recipeRevision','identityRevision','sourceDigest','compilerVersion','templateVersion','files','localPreflight','externalStatus','semanticSummary','externalStatement'],'$');
  if(manifest.format!=='my-avatars-roblox-classic-package'||manifest.version!==1||!Number.isInteger(manifest.recipeRevision)||manifest.recipeRevision<1||!Number.isInteger(manifest.identityRevision)||manifest.identityRevision<1||!DIGEST.test(manifest.sourceDigest)||manifest.compilerVersion!=='roblox-classic-v1'||manifest.templateVersion!==ROBLOX_CLASSIC_TEMPLATE_V1.version||manifest.externalStatus!=='not-submitted'||manifest.externalStatement!=='Roblox import, moderation, compatibility, and publication are external.')throw new TypeError('Manifest scalar field is invalid');
  dense(manifest.files,'$.files');if(manifest.files.length!==2)throw new TypeError('Manifest files must have two records');const expected=['my-avatar-roblox-pants.png','my-avatar-roblox-shirt.png'];manifest.files.forEach((file,index)=>{exact(file,['filename','pixelDigest','width','height'],`$.files[${index}]`);if(file.filename!==expected[index]||!DIGEST.test(file.pixelDigest)||file.width!==585||file.height!==559)throw new TypeError('Manifest file record is invalid');});
  validateLocalPreflightReportV1(manifest.localPreflight);if(manifest.localPreflight.passed!==manifest.localPreflight.checks.every(({passed})=>passed)||manifest.localPreflight.checks.length!==6||manifest.localPreflight.checks.some(({id},index)=>id!==LOCAL_IDS[index]))throw new TypeError('Manifest local preflight is inconsistent');
  exact(manifest.semanticSummary,['top','bottom','footwear','outerwear'],'$.semanticSummary');validateSemanticPalette(manifest.semanticSummary.top,'$.semanticSummary.top');validateSemanticPalette(manifest.semanticSummary.bottom,'$.semanticSummary.bottom');validateSemanticPalette(manifest.semanticSummary.footwear,'$.semanticSummary.footwear');if(typeof manifest.semanticSummary.outerwear!=='boolean')throw new TypeError('Manifest outerwear must be boolean');
  return manifest;
}

const manifestFor=async(snapshot,shirt,pants,localPreflight)=>({
  format:'my-avatars-roblox-classic-package',version:1,recipeRevision:snapshot.recipeRevision,identityRevision:snapshot.identityRevision,sourceDigest:snapshot.sourceDigest,
  compilerVersion:'roblox-classic-v1',templateVersion:ROBLOX_CLASSIC_TEMPLATE_V1.version,
  files:[{filename:'my-avatar-roblox-pants.png',pixelDigest:await digestBytes(pants),width:585,height:559},{filename:'my-avatar-roblox-shirt.png',pixelDigest:await digestBytes(shirt),width:585,height:559}],
  localPreflight,externalStatus:'not-submitted',
  semanticSummary:{top:snapshot.semanticAppearance.outfit.top,bottom:snapshot.semanticAppearance.outfit.bottom,footwear:snapshot.semanticAppearance.outfit.footwear,outerwear:snapshot.semanticAppearance.outfit.outerwear},
  externalStatement:'Roblox import, moderation, compatibility, and publication are external.',
});

export function createRobloxClassicCompiler(){return Object.freeze({
  async compile(input){let snapshot,profile;try{({snapshot,profile}=readInput(input));validateAppearanceSnapshotV1(snapshot);}catch(error){return fault('invalid-snapshot',error);}try{validateRobloxClassicProfileV1(profile);if(profile.blockAvatarNoticeAccepted!==true)throw new TypeError('Block Avatar notice must be accepted');}catch(error){return fault('invalid-profile',error);}try{
    const shirt=paintRobloxClassic(snapshot,'shirt'),pants=paintRobloxClassic(snapshot,'pants');const localPreflight=createRobloxLocalPreflight({width:585,height:559,rgba:shirt},{width:585,height:559,rgba:pants});if(!localPreflight.passed)throw new TypeError('Local canvas preflight failed');const shirtPng=encodePngRgba(585,559,shirt),pantsPng=encodePngRgba(585,559,pants),manifest=await manifestFor(snapshot,shirt,pants,localPreflight);validateRobloxPackageManifest(manifest);const manifestText=canonicalJson(manifest);if(prohibited.test(`${manifestText}\n${ROBLOX_CLASSIC_README}`))throw new TypeError('Package text contains a prohibited claim');const zip=createStoredZip([{name:'my-avatar-roblox-shirt.png',bytes:shirtPng},{name:'my-avatar-roblox-pants.png',bytes:pantsPng},{name:'manifest.json',bytes:utf8(manifestText)},{name:'README.txt',bytes:utf8(ROBLOX_CLASSIC_README)}]);const bundle={compiler:'roblox-classic-v1',sourceDigest:snapshot.sourceDigest,artifacts:[{filename:'my-avatar-roblox-classic.zip',mediaType:'application/zip',bytes:zip}]};validateArtifactBundleV1(bundle);return ok(bundle);
  }catch(error){return fault('render-failed',error);}},
  async preflight(bundle){const checks=[];try{validateArtifactBundleV1(bundle);checks.push(check('bundle',bundle.compiler==='roblox-classic-v1'&&bundle.artifacts.length===1,'Roblox bundle contract and compiler match.'));if(!checks.at(-1).passed)throw new TypeError('Bundle compiler or artifact count mismatch');const artifact=bundle.artifacts[0];if(artifact.filename!=='my-avatar-roblox-classic.zip'||artifact.mediaType!=='application/zip')throw new TypeError('ZIP artifact metadata mismatch');const entries=parseStoredZip(artifact.bytes);checks.push(check('entries',entries.length===4&&entries.every((entry,index)=>entry.name===EXPECTED[index]),'ZIP has exact sorted entries.'));if(!checks.at(-1).passed)throw new TypeError('ZIP entry set mismatch');const shirt=decodePngRgba(entries.find(({name})=>name==='my-avatar-roblox-shirt.png').bytes),pants=decodePngRgba(entries.find(({name})=>name==='my-avatar-roblox-pants.png').bytes);const recomputed=createRobloxLocalPreflight(shirt,pants);checks.push(...recomputed.checks);const rawManifest=text(entries.find(({name})=>name==='manifest.json').bytes),manifest=JSON.parse(rawManifest);validateRobloxPackageManifest(manifest);const manifestFiles=manifest.files[0].pixelDigest===await digestBytes(pants.rgba)&&manifest.files[1].pixelDigest===await digestBytes(shirt.rgba);checks.push(check('manifest',rawManifest===canonicalJson(manifest)&&manifest.sourceDigest===bundle.sourceDigest&&manifestFiles&&canonicalJson(manifest.localPreflight)===canonicalJson(recomputed),'Manifest is canonical and consistent with recomputed local preflight.'));const readme=text(entries.find(({name})=>name==='README.txt').bytes);checks.push(check('readme',readme===ROBLOX_CLASSIC_README&&!prohibited.test(`${readme}\n${rawManifest}`)&&!/photo|provenance|face|hair|credential/i.test(rawManifest),'README and manifest are privacy-safe and claim-safe.'));
  }catch(error){checks.push(check('package',false,error.message));}return Object.freeze({passed:checks.length>0&&checks.every(({passed})=>passed),checks:Object.freeze(checks.map(Object.freeze))});}
});}
